### ISSUE TITLE
barstools doesn't build against latest FIRRTL

### ISSUE THREAD

**Issue by stevobailey** [ucb-bar/barstools#18]
Looks like FIRRTL changed "PassBased" trait to "SeqTransformBased" and "runPasses" was replaced with "runTransforms" though it takes as input the state, not the circuit, now. 

Maybe the FIRRTL changes should include the old code, with deprecation warnings? 

@azidar @colinschmidt @grebe @shunshou @chick

**Comment by colinschmidt** [comment]
I'm checking this out now since its blocking me

**Comment by shunshou** [comment]
I merged @chick 's changes that should've fixed it. But I also merged @stevobailey 's AnalogAnnotations branch. It worked b/c I'm on @grebe 's firrtl branch, but otherwise, it'd derp... My bad :(

**Comment by colinschmidt** [comment]
So maybe a13869b6aa5b0c5da00d974c4de7229ad400834a will work with new FIRRTL API? trying it out. My attempted port kept running into ucb-bar/firrtl#519 so I'm glad @chick was able to get it working.

**Comment by shunshou** [comment]
Hm so I'm using a slightly older branch of Firrtl (but with Paul's changes
-- this is getting really confusing), so idk if that'd solve your problem.
I'll remove the analog stuff and just point to a separate branch that pulls
in master I guess... Sorry about that!

**Comment by colinschmidt** [comment]
Yeah it still doesn't work, but don't worry about it for my sake.

**Comment by colinschmidt** [comment]
Ah ok so It turns out @azidar was able to help me find the issue, and I've PR'd the fix in firrtl

**Comment by chick** [comment]
@stevobailey can this be closed now?

**Comment by stevobailey** [comment]
I think so, though I haven't imported this to craft. That's fine, though

**Comment by edwardcwang** [comment]
Can we close this now?

**Comment by stevobailey** [comment]
Yup.
